export const GET_ALL_POKEMONS = 'GET_ALL_POKEMONS';
export const GET_POKEMON_DETAIL = 'GET_POKEMON_DETAIL';
export const GET_POKEMON_BY_NAME =  'GET_POKEMON_BY_NAME';
export const CLEAR_DETAIL = 'CLEAR_DETAIL';                     // Limpia el estado global "Pokemon"
export const FILTER = 'FILTER';
export const FILTER_BY_ORIGIN = 'FILTER_BY_ORIGIN';
export const ORDER_BY_ASC = 'ORDER_BY_ASC';
export const ORDER_BY_DESC = 'ORDER_BY_DESC';
export const GET_TYPES = 'GET_TYPES';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';                     // Limpia el estado global de mensajes del Back
export const CREATE_POKEMON = 'CREATE_POKEMON';
export const DELETE_POKEMON = 'DELETE_POKEMON'